name: Build
on: push

jobs:
  build-asi:
    # https://github.com/actions/virtual-environments#available-environments
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2
      # with:
      #   vs-version: '[16.4,16.5)'

    - name: Build
      run: |
        msbuild *.sln /property:Configuration=Debug
        msbuild *.sln /property:Configuration=Release

    - name: Upload build as artifact
      uses: actions/upload-artifact@v2
      with:
        name: build
        path: |
          Debug/
          Release/